신경망에서의 기울기

In [1]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [9]:
net = simpleNet()
print(net.W)

[[ 0.30763252  0.11668153 -1.32738169]
 [ 1.66902013  1.59593855 -0.27102574]]


In [10]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)
print(np.argmax(p))
t = np.array([0, 0, 1])
print(net.loss(x, t))

[ 1.68669763  1.50635361 -1.04035218]
0
3.3691086068567127


In [11]:
def f(W):
    return net.loss(x, t)
## dummy function

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.31572294  0.26362326 -0.57934619]
 [ 0.4735844   0.39543489 -0.86901929]]
